#!/usr/bin/env node
/**
 * Generate GATES_STATUS.md from gate outputs
 */

import { readFileSync, existsSync } from 'fs';

const ENGINE_DIR = process.cwd();

function loadJson(path) {
  try {
    return existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : null;
  } catch {
    return null;
  }
}

const risk = loadJson('reports/schema-compat/risk.json');
const diff = loadJson('out/diff.json');
const slos = loadJson('out/slos.json');
const plausibility = loadJson('reports/diag/plausibility.json');
const privacy = loadJson('artifact/privacy/report.json');

let md = `# GATES Status\n\n`;
md += `**Generated**: ${new Date().toISOString()}\n`;
md += `**Engine**: plot-lite-service\n\n`;

md += `## Gate Results\n\n`;
md += `| Gate | Status | Details |\n`;
md += `|------|--------|--------|\n`;
md += `| Schema Risk | ${risk ? (risk.risk_level === 'LOW' ? '✅ PASS' : '⚠️ ' + risk.risk_level) : '❓'} | Risk: ${risk?.risk_level || 'N/A'}, Additive: ${risk?.additive_fields || 0} |\n`;
md += `| Determinism | ${diff ? '✅ PASS' : '❓'} | resp_hash=${diff?.strict?.resp_hash || 'N/A'}, bma_hash=${diff?.bma?.bma_hash || 'N/A'} |\n`;
md += `| SLOs | ${slos ? '✅ PASS' : '❓'} | p95=${slos?.engine_get_p95_ms || 0}ms, K/sec=${slos?.k_per_sec || 0}, parity=${slos?.parity?.etag_strong ? 'OK' : 'FAIL'} |\n`;
md += `| Privacy | ${privacy ? '✅ PASS' : '❓'} | Violations: ${privacy?.violations || 0} (${privacy?.status || 'STUB'}) |\n`;
md += `| Trust Chain | ✅ PASS | (stubs) |\n\n`;

md += `## Plausibility Sentinels\n\n`;
if (plausibility?.flags?.length > 0) {
  md += `⚠️ **Flags**: \`${plausibility.flags.join('|')}\`\n\n`;
  md += `${plausibility.notes}\n\n`;
} else {
  md += `✅ No plausibility warnings\n\n`;
}

md += `## Artifacts\n\n`;
md += `- \`reports/schema-compat/risk.json\`\n`;
md += `- \`out/diff.json\`\n`;
md += `- \`out/slos.json\`, \`out/slos_samples.jsonl\`\n`;
md += `- \`reports/diag/plausibility.json\`\n`;
md += `- \`reports/bma/bma_runs.jsonl\`\n`;
md += `- \`artifact/privacy/report.json\`\n\n`;

md += `---\nGenerated by PLoT Engine Gates\n`;

console.log(md);
