/**
 * Drive every PLoT producer that sends a request to ISL, and capture the EXACT
 * bytes handed to `fetch`.
 *
 * Contract step-2 slice 2 (request-side drift pairing). Shared by:
 *   - tests/isl-request-drift-pairing.contract.test.ts  (the standing gate)
 *   - tools/isl-contract/capture-egress.ts              (regenerates the fixtures
 *     that the pinned-model replay driver consumes)
 *
 * WHY THE FETCH BOUNDARY (rule 3 / trap 16). `ISLClient.request()` builds
 * `requestBodyText = JSON.stringify(body)` (client.ts) and hands that exact
 * string to fetch. A harness that asserted on a translator's RETURN value would
 * sit upstream of the boundary and could not see a key re-added downstream —
 * the constraint injector and the flip-probe cloner both mutate after the
 * translator has returned. Everything here is captured at the wire.
 *
 * DETERMINISM is a hard requirement: the same bodies are hashed into
 * `tests/fixtures/isl-pinned/replay-transcript.json` by the Python driver, and
 * the standing test re-derives them and compares hashes. Every input below is
 * therefore fixed — no clocks, no randomness, no ambient env. `request_id` and
 * `seed` are literals.
 */

import { createHash } from 'node:crypto';

import { ISLClient } from '../../src/integrations/isl/client.js';
import {
  toISLRobustnessRequest,
  type ISLRobustnessRequestV3,
} from '../../src/integrations/isl/translator-v3.js';
import { injectConstraintParameterUncertainties } from '../../src/integrations/isl/constraint-pu-injection.js';
import { createISLInferenceFn } from '../../src/analysis/flip-thresholds.js';
import { createISLService } from '../../src/integrations/isl/index.js';
import type {
  EngineGraphV3,
  EngineNodeV3,
  OptionV3,
  GoalConstraint,
} from '../../src/types/engine-v3.js';

// -----------------------------------------------------------------------------
// Capture
// -----------------------------------------------------------------------------

export interface EgressCapture {
  /** The full URL string given to fetch. */
  url: string;
  /** The ISL endpoint path, e.g. `/api/v1/robustness/analyze/v2`. */
  endpoint: string;
  /** The exact string given to fetch as the request body. */
  bodyText: string;
  /** `JSON.parse(bodyText)`. */
  body: unknown;
}

const ISL_BASE_URL = 'https://isl.pinned.test';

function endpointOf(url: string): string {
  return url.startsWith(ISL_BASE_URL) ? url.slice(ISL_BASE_URL.length) : url;
}

let captured: EgressCapture[] = [];
let realFetch: typeof globalThis.fetch | undefined;

/**
 * Replace global fetch with a recorder. Deliberately a PLAIN assignment rather
 * than `vi.stubGlobal`, so this module also runs outside vitest — the same
 * producers are driven by `tools/isl-contract/capture-egress.ts` under tsx to
 * regenerate the fixtures the Python replay driver reads. One harness, one set
 * of bytes; a second hand-written copy for the tool would be the mirror defect
 * this whole slice exists to remove.
 */
export function installEgressCapture(responseBody: unknown = { status: 'ok' }): void {
  captured = [];
  if (realFetch === undefined) realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: unknown, init: { body?: unknown } | undefined) => {
    const bodyText = String(init?.body ?? '');
    captured.push({
      url: String(url),
      endpoint: endpointOf(String(url)),
      bodyText,
      body: JSON.parse(bodyText),
    });
    return {
      ok: true,
      status: 200,
      headers: { get: () => null },
      text: async () => JSON.stringify(responseBody),
      json: async () => responseBody,
    } as unknown as Response;
  }) as typeof globalThis.fetch;
}

export function uninstallEgressCapture(): void {
  if (realFetch !== undefined) globalThis.fetch = realFetch;
  captured = [];
}

export function takeCaptured(): EgressCapture[] {
  const out = captured;
  captured = [];
  return out;
}

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/**
 * The committed fixture form. `wire_bytes_sha256` pins the EXACT string handed
 * to fetch; `body` is the same content parsed, which is what the Python replay
 * driver feeds to the pinned model (JSON formatting cannot change a Pydantic
 * parse, but it would change a hash, so both are recorded).
 */
export function canonicalEgressFixture(producer: ProducerSpec, capture: EgressCapture): string {
  return `${JSON.stringify(
    {
      _README:
        'GENERATED by tools/isl-contract/capture-egress.ts — do not hand-edit. Regenerate, then re-run tools/isl-contract/replay-through-pinned-model.py.',
      producer: producer.name,
      endpoint: producer.endpoint,
      site: producer.site,
      liveness: producer.liveness,
      note: producer.note,
      wire_bytes_length: capture.bodyText.length,
      wire_bytes_sha256: sha256(capture.bodyText),
      body: capture.body,
    },
    null,
    2,
  )}\n`;
}

function newClient(): ISLClient {
  return new ISLClient({
    baseUrl: ISL_BASE_URL,
    apiKey: 'pinned-test-key',
    timeoutMs: 5_000,
    maxRetries: 1,
  });
}

// -----------------------------------------------------------------------------
// Fixture graph — chosen to exercise EVERY branch that can put a key on the wire
// -----------------------------------------------------------------------------

/**
 * `metadata` is what PLoT's own normaliser attaches to a constraint node's
 * observed_state (graph-normaliser.ts) so the constraint compiler can read
 * `.operator`. It is PLoT-internal and must not reach ISL. It is not declared on
 * `EngineNodeV3.observed_state`, hence the cast — which is exactly why the
 * pre-slice-6 verbatim forward was invisible to the typechecker.
 */
function nodeWithInternalMetadata(): EngineNodeV3 {
  return {
    id: 'fac_headcount',
    kind: 'factor',
    label: 'Headcount',
    observed_state: {
      value: 0.4,
      std: 0.08,
      baseline: 0.3,
      unit: 'people',
      raw_value: 40,
      cap: 100,
      factor_type: 'quantitative',
      uncertainty_drivers: ['hiring_pipeline'],
      metadata: { operator: '<=', source: 'cee_constraint_node' },
    } as EngineNodeV3['observed_state'],
  } as EngineNodeV3;
}

export function buildGraph(): EngineGraphV3 {
  const nodes: EngineNodeV3[] = [
    nodeWithInternalMetadata(),
    // External factor with a uniform prior → PU synthesised from the range.
    {
      id: 'fac_market',
      kind: 'factor',
      label: 'Market growth',
      category: 'external',
      prior: { distribution: 'uniform', range_min: 0.2, range_max: 0.6 },
    } as EngineNodeV3,
    // Constrained node with no PU of its own → constraint injection fires.
    {
      id: 'fac_cost',
      kind: 'factor',
      label: 'Cost',
      observed_state: { value: 0.55 },
    } as EngineNodeV3,
    // In the graph but with no observed_state, so the translator emits no PU for
    // it — the realistic "insert" branch of the flip probe.
    { id: 'fac_no_obs', kind: 'factor', label: 'Unmeasured' } as EngineNodeV3,
    { id: 'goal_margin', kind: 'outcome', label: 'Margin' } as EngineNodeV3,
  ];

  return {
    nodes,
    edges: [
      {
        from: 'fac_headcount',
        to: 'goal_margin',
        exists_probability: 0.9,
        strength: { mean: 0.5, std: 0.1 },
      },
      {
        from: 'fac_market',
        to: 'goal_margin',
        exists_probability: 0.8,
        strength: { mean: 0.3, std: 0.12 },
      },
      {
        from: 'fac_cost',
        to: 'goal_margin',
        exists_probability: 0.85,
        strength: { mean: -0.4, std: 0.09 },
      },
    ],
  } as EngineGraphV3;
}

/**
 * The `/v1/run` leg reaches ISL through `analyseRobustness`, which consumes the
 * trust-layer `Graph` (edges carry `weight` / `belief_exists` / `strength_std`,
 * not a `strength` object).
 */
function buildV1Graph(): Parameters<ReturnType<typeof createISLService>['analyseRobustness']>[0] {
  return {
    nodes: [
      nodeWithInternalMetadata(),
      { id: 'fac_cost', kind: 'factor', label: 'Cost', observed_state: { value: 0.55, std: 0.05 } },
      { id: 'goal_margin', kind: 'outcome', label: 'Margin' },
    ],
    edges: [
      { from: 'fac_headcount', to: 'goal_margin', weight: 0.5, belief_exists: 0.9, strength_std: 0.1 },
      { from: 'fac_cost', to: 'goal_margin', weight: -0.4, belief_exists: 0.85, strength_std: 0.09 },
    ],
  } as never;
}

const OPTIONS: OptionV3[] = [
  { id: 'opt_a', label: 'Hire', interventions: { fac_headcount: { value: 0.8 } } },
  { id: 'opt_b', label: 'Hold', interventions: { fac_headcount: { value: 0.2 } } },
] as unknown as OptionV3[];

/** Golden-path constraints: `constraint_id` present, `weight` absent. */
const CONSTRAINTS: GoalConstraint[] = [
  { constraint_id: 'c1', node_id: 'fac_cost', operator: '<=', value: 0.7, label: 'Cost cap' },
] as unknown as GoalConstraint[];

/**
 * Caller-supplied `weight`. `PLOT_TO_ISL_CONTRACT.knownUndeclared` exempts
 * `goal_constraints[].weight`, and an exemption for a key no producer can emit
 * is a dead entry that would never be noticed. This variant makes the exemption
 * OBSERVABLE, so the stale-exemption check below is not vacuous.
 */
const CONSTRAINTS_WITH_WEIGHT: GoalConstraint[] = [
  { constraint_id: 'c1', node_id: 'fac_cost', operator: '<=', value: 0.7, label: 'Cost cap', weight: 0.6 },
] as unknown as GoalConstraint[];

function buildV2Request(constraints: GoalConstraint[]): ISLRobustnessRequestV3 {
  const graph = buildGraph();
  const request = toISLRobustnessRequest(
    graph,
    OPTIONS,
    'goal_margin',
    'req_slice2_pairing',
    2000,
    undefined,
    constraints,
    'seed-slice2',
  );
  // /v2/run runs this immediately after building the request (run.ts Phase 4b+);
  // it MUTATES request.parameter_uncertainties, so a translator-only capture
  // would miss the entries it adds.
  injectConstraintParameterUncertainties(request, constraints, graph.nodes, 'goal_margin');
  return request;
}

// -----------------------------------------------------------------------------
// The producer manifest
// -----------------------------------------------------------------------------

export type ProducerLiveness = 'live' | 'dead-no-caller';

export interface ProducerSpec {
  /** Stable fixture name; also the filename under tests/fixtures/isl-pinned/egress/. */
  name: string;
  /** ISL endpoint this producer targets. */
  endpoint: string;
  /** Where the call is made from, file:symbol. */
  site: string;
  /** Whether the producer has a live caller in PLoT at this tip. */
  liveness: ProducerLiveness;
  /** Human note carried into the PR/report. */
  note: string;
  /** Drives the producer; returns every body it put on the wire. */
  run: () => Promise<EgressCapture[]>;
}

/** `createISLService()` reads its config from env at construction. */
function enabledService(): ReturnType<typeof createISLService> {
  process.env.ISL_ENABLE = '1';
  process.env.ISL_BASE_URL = ISL_BASE_URL;
  process.env.ISL_API_KEY = 'pinned-test-key';
  return createISLService();
}

async function runV2Base(constraints: GoalConstraint[]): Promise<EgressCapture[]> {
  await newClient().request({
    endpoint: '/api/v1/robustness/analyze/v2',
    body: buildV2Request(constraints),
    requestId: 'req_slice2_pairing',
  });
  return takeCaptured();
}

/**
 * Every PLoT → ISL request producer that can be driven end-to-end to the fetch
 * boundary, in a fixed order. `capture-egress.ts` writes one fixture per entry.
 *
 * NOT here, deliberately, and covered by the endpoint-manifest test instead:
 *   - `/api/v1/analysis/thresholds` (routes/v2/run.ts). Its payload is built
 *     inline inside the /v2/run handler and is not reachable without standing up
 *     the whole route; and ISL does not MOUNT that path at the pin, so there is
 *     no request model to pair its keys against. See the manifest test.
 */
export const PRODUCERS: ProducerSpec[] = [
  {
    name: 'v2-run-base',
    endpoint: '/api/v1/robustness/analyze/v2',
    site: 'routes/v2/run.ts → islService.callAnalysisEndpoint',
    liveness: 'live',
    note: 'The base /v2/run analysis body — the highest-traffic ISL request PLoT sends.',
    run: () => runV2Base(CONSTRAINTS),
  },
  {
    name: 'v2-run-base-constraint-weight',
    endpoint: '/api/v1/robustness/analyze/v2',
    site: 'routes/v2/run.ts → islService.callAnalysisEndpoint (caller supplied constraint weight)',
    liveness: 'live',
    note: 'Same producer with a caller-supplied goal_constraints[].weight, so the second knownUndeclared exemption is observable rather than latent.',
    run: () => runV2Base(CONSTRAINTS_WITH_WEIGHT),
  },
  {
    name: 'flip-probe-clone',
    endpoint: '/api/v1/robustness/analyze/v2',
    site: 'analysis/flip-thresholds.ts → createISLInferenceFn (probe on a factor already in the PU list)',
    liveness: 'live',
    note: 'The flip probe CLONES the base request and mutates it, downstream of the translator.',
    run: async () => {
      const original = buildV2Request(CONSTRAINTS);
      const client = newClient();
      const inferenceFn = createISLInferenceFn(
        async (endpoint, body, requestId, signal) => {
          const res = await client.request<unknown>({ endpoint, body, requestId, signal });
          return { data: res.data };
        },
        original as never,
        'req_slice2_pairing',
      );
      await inferenceFn('fac_headcount', 0.75);
      return takeCaptured();
    },
  },
  {
    name: 'flip-probe-insert',
    endpoint: '/api/v1/robustness/analyze/v2',
    site: 'analysis/flip-thresholds.ts → createISLInferenceFn (probe on a graph factor with no PU)',
    liveness: 'live',
    note: 'The other branch of the probe: it INSERTS a PU entry the translator never produced.',
    run: async () => {
      const original = buildV2Request(CONSTRAINTS);
      const client = newClient();
      const inferenceFn = createISLInferenceFn(
        async (endpoint, body, requestId, signal) => {
          const res = await client.request<unknown>({ endpoint, body, requestId, signal });
          return { data: res.data };
        },
        original as never,
        'req_slice2_pairing',
      );
      await inferenceFn('fac_no_obs', 0.25);
      return takeCaptured();
    },
  },
  {
    name: 'v1-run-analyse-robustness',
    endpoint: '/api/v1/robustness/analyze/v2',
    site: 'integrations/isl/index.ts → analyseRobustness (called from routes/v1/run.ts)',
    liveness: 'live',
    note: 'The second live producer: a DIFFERENT request builder over the trust-layer graph shape.',
    run: async () => {
      const service = enabledService();
      await service.analyseRobustness(
        buildV1Graph(),
        'goal_margin',
        [
          { id: 'opt_a', label: 'Hire', interventions: { fac_headcount: 0.8 } },
          { id: 'opt_b', label: 'Hold', interventions: { fac_headcount: 0.2 } },
        ],
        'req_slice2_pairing_v1',
      );
      return takeCaptured();
    },
  },
  {
    name: 'factor-sensitivity-dead',
    endpoint: '/api/v1/robustness/analyze/v2',
    site: 'integrations/isl/index.ts → analyseFactorSensitivity',
    liveness: 'dead-no-caller',
    note: 'No caller outside its own module at this tip (slice-6 finding 3). Captured anyway: it targets a MOUNTED endpoint, so it is pairable, and pairing it while it is dark stops it rotting further.',
    run: async () => {
      const service = enabledService();
      await service.analyseFactorSensitivity(
        buildV1Graph(),
        [{ node_id: 'fac_cost', distribution: 'normal', std: 0.05 }],
        'goal_margin',
        [
          { id: 'opt_a', label: 'Hire', interventions: { fac_headcount: 0.8 } },
          { id: 'opt_b', label: 'Hold', interventions: { fac_headcount: 0.2 } },
        ],
        'req_slice2_pairing_fs',
      );
      return takeCaptured();
    },
  },
  {
    name: 'causal-validate',
    endpoint: '/api/v1/causal/validate',
    site: 'integrations/isl/index.ts → validateCausal (called from routes/v1/run.ts)',
    liveness: 'live',
    note: 'LIVE producer targeting an endpoint ISL does NOT mount at the pin. See the endpoint-manifest test.',
    run: async () => {
      const service = enabledService();
      await service.validateCausal(buildV1Graph(), 'fac_headcount', 'goal_margin', 'req_slice2_validate');
      return takeCaptured();
    },
  },
  {
    name: 'causal-sensitivity-detailed-dead',
    endpoint: '/api/v1/causal/sensitivity/detailed',
    site: 'integrations/isl/index.ts → analyseSensitivity',
    liveness: 'dead-no-caller',
    note: 'No caller at this tip (routes/v1/run.ts comments record it was replaced by analyseRobustness). ISL does not mount the endpoint either.',
    run: async () => {
      const service = enabledService();
      await service.analyseSensitivity(buildV1Graph(), 'fac_headcount', 'goal_margin', 'req_slice2_sens');
      return takeCaptured();
    },
  },
  {
    name: 'causal-counterfactual-dead',
    endpoint: '/api/v1/causal/counterfactual',
    site: 'integrations/isl/index.ts → computeCounterfactual',
    liveness: 'dead-no-caller',
    note: 'No caller at this tip, but the endpoint IS mounted — so its body is pairable against CounterfactualRequest, and the pairing has something to say about it.',
    run: async () => {
      const service = enabledService();
      await service.computeCounterfactual(
        buildV1Graph(),
        { fac_headcount: 0.8 },
        'goal_margin',
        'req_slice2_cf',
      );
      return takeCaptured();
    },
  },
];
