name: Cache Consistency

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cache-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Cache consistency
        run: node tools/cache-check.js
        continue-on-error: true

      - name: Upload cache check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cache-check
          path: reports/cache-check.json
          if-no-files-found: warn
