name: Contract Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  contract-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Contract coverage
        run: node tools/contract-coverage.js
        continue-on-error: true

      - name: Upload contract coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contract-coverage
          path: reports/contract-coverage.json
          if-no-files-found: warn
