name: Docker Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build and Trivy scan
        run: node tools/docker-build-check.js
        continue-on-error: true

      - name: Upload Docker build report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-build
          path: |
            reports/docker-build.json
            reports/trivy.json
          if-no-files-found: warn
