name: Docs Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-links:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docs link check
        run: node tools/docs-link-check.js
        continue-on-error: true

      - name: Upload docs link report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-link-check
          path: reports/docs-link-check.json
          if-no-files-found: warn
