name: engine-safety
on:
  push:
  pull_request:
jobs:
  safety:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install (if needed)
        run: |
          if [ -f package.json ]; then npm ci || true; fi
      - name: Run engine tests
        run: node tools/run-tests.cjs
      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: reports/tests.json
