name: Nightly Smoke (Gated)

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nightly smoke (gated by TEST_BASE_URL)
        run: node tools/smoke.js
        continue-on-error: true
        env:
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL }}

      - name: Upload smoke report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke
          path: reports/smoke.json
          if-no-files-found: warn
