name: tests-smoke
on:
  push:
    paths:
      - 'src/engine/**'
      - 'tools/**'
      - 'test/engine/**'
      - 'docs/plot-lite-engine/**'
      - 'openapi/schemas/**'
      - '.github/workflows/tests-smoke.yml'
  pull_request:
permissions: { contents: read }
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install (if needed)
        run: |
          if [ -f package.json ]; then npm ci || true; fi
      - name: Run engine tests
        run: node tools/run-tests.cjs
      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: reports/tests.json
          if-no-files-found: warn
      - name: Upload fuzz repro (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-repro
          path: reports/warp/fuzz-last.json
          if-no-files-found: ignore
